#!/usr/bin/env python

import json
import redis
from pymongo import MongoClient

REDIS_PREFIX = "conspiracy:pages:"
REDIS_PAGEID_PREFIX = "conspiracy:pages:id:"

REMOTE_REDIS_HOST = '10.151.12.22'

print 'Grabbing redis...'

redis_clients = [
  redis.StrictRedis(host='localhost', port=6379, db=1),
  redis.StrictRedis(host=REMOTE_REDIS_HOST, port=6379, db=1)
]

all_articles = []
for client in redis_clients:
  keys = client.keys(REDIS_PAGEID_PREFIX + '*')
  for key in keys:
    obj = json.loads(client.get(key))
    obj['permalink_id'] = key[key.rfind(':')+1:]
    all_articles.append(obj)

print 'Connecting to mongo...'

mongoconn = MongoClient()
db = mongoconn.verified_facts
coll = db.articles
coll.ensure_index('permalink_id', unique=True)

print 'Copying redis args to mongo'

coll.insert(all_articles)
